name: Prebuild Binaries

on:
  pull_request:

jobs:
  prebuild-linux:
    name: Prebuild Binaries for Linux
    runs-on: ubuntu-latest
    timeout-minutes: 30
    steps:
      - name: Setup Dependencies
        run: |
          sudo dpkg --add-architecture i386
          sudo apt-get update -y -qq
          sudo apt-get install -y g++-multilib gcc-multilib libcups2-dev libcups2-dev:i386 libc6-dev-i386 linux-libc-dev linux-libc-dev:i386
            - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18.x
          registry-url: https://npm.pkg.github.com
          scope: '@casamagalhaes'
          cache: npm

      - run: npm ci
      - name: Prebuild
        run: |
          npm run apply-patches
          npm run prebuild -- --strip -t 18.0.0 --arch ia32
          npm run prebuild -- --strip -t 18.0.0 --arch x64
  prebuild-macos:
    name: Prebuild Binaries for macOS
    runs-on: macos-latest
    timeout-minutes: 30
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18.x
          registry-url: https://npm.pkg.github.com
          scope: '@casamagalhaes'
          cache: npm

      - run: npm ci
      - name: Prebuild
        run: |
          npm run apply-patches
          npm run prebuild -- --strip -t 18.0.0 --arch x64
  prebuild-windows:
    name: Prebuild Binaries for Windows
    runs-on: windows-latest
    timeout-minutes: 30
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18.x
          registry-url: https://npm.pkg.github.com
          scope: '@casamagalhaes'
          cache: npm

      - run: npm ci
      - name: Prebuild
        run: |
          npm run apply-patches
          npm run prebuild -- --strip -t 18.0.0 --arch ia32
          npm run prebuild -- --strip -t 18.0.0 --arch x64
